trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish Build Artifacts'

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'MySonarQubeServiceConnection' # Replace with your SonarQube service connection
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'your-project-key'
    cliProjectName: 'Your Project Name'
    cliSources: 'src'
  displayName: 'Prepare SonarQube analysis'

- script: |
    # Additional deployment scripts or commands
    # e.g., deploy to Azure, Heroku, etc.
  displayName: 'Deploy'

- task: SonarQubeAnalyze@4
  displayName: 'Run SonarQube analysis'
